### ISSUE TITLE
Could you make it compatible with godot 4.0?

### ISSUE THREAD

**Issue by DanielSchimit** [RodZill4/godot-procedural3d#3]
Dear, I really liked your plugin I want to use it in my game and put it in the credits of my game that you made? when i use 3.4.4 i can't see textures and my doll falls into infinity. I really hope you can help me...

**Comment by RodZill4** [comment]
This project should work in 3.4.4 right away. Did you try to use it with your own assets?

I didn't port this to Godot 4.0 yet but will probably do it when 4.0 is available.

**Comment by DanielSchimit** [comment]
gametest\procedural3d_demo\models\src 

assets are included, are there other assets? what do you think might be happening?
